//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTheWeatherEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataWeather
    {
        public int Id { get; set; }
        public string weather { get; set; }
        public string weatherDescription { get; set; }
        public string windDeg { get; set; }
        public Nullable<double> middleTemp { get; set; }
        public Nullable<double> windSpeed { get; set; }
        public Nullable<double> humidity { get; set; }
        public Nullable<double> pressure { get; set; }
        public string time { get; set; }
        public string Date { get; set; }
    }
}
